export default function MobileMenuOnc() {
    const ThisMobileMenu = document.querySelector(".ThisMobileMenu");
    const menuolVMiniO = document.querySelector(".menuolVMiniO");
    const menuolVMiniS = document.querySelector(".menuolVMiniS");
    const menuolVMiniT = document.querySelector(".menuolVMiniT");
    const menuolVMiniD = document.querySelector(".menuolVMiniF");
    const menuolUMiniO = document.querySelector(".menuolVMiniS");
    const menuolPodMiniS = document.querySelector(".menuolPodMiniS");
    const menuolPodMiniT = document.querySelector(".menuolPodMiniT");
    const menuolPodMiniF = document.querySelector(".menuolPodMiniF");
    const facaretdownO = document.querySelector(".fa-caret-downO");
    const facaretdownS = document.querySelector(".fa-caret-downS");
    const facaretdownT = document.querySelector(".fa-caret-downT");
    const facaretdownF = document.querySelector(".fa-caret-downF");
    ThisMobileMenu.classList.toggle("active");
    menuolVMiniO.classList.remove("activeOL");
    menuolVMiniS.classList.remove("activeOL");
    menuolVMiniT.classList.remove("activeOL");
    menuolVMiniD.classList.remove("activeOL");
    menuolUMiniO.classList.remove("activeLi");
    menuolPodMiniS.classList.remove("activeLi");
    menuolPodMiniT.classList.remove("activeLi");
    menuolPodMiniF.classList.remove("activeLi");
    facaretdownO.classList.remove("activeFa");
    facaretdownS.classList.remove("activeFa");
    facaretdownT.classList.remove("activeFa");
    facaretdownF.classList.remove("activeFa");
}

export function menuolMiniO() {
    const menuolVMiniO = document.querySelector(".menuolVMiniO");
    const menuolUMiniO = document.querySelector(".menuolUMiniO");
    const menuolVMiniS = document.querySelector(".menuolVMiniS");
    const menuolVMiniT = document.querySelector(".menuolVMiniT");
    const menuolVMiniD = document.querySelector(".menuolVMiniF");
    const menuolPodMiniS = document.querySelector(".menuolPodMiniS");
    const menuolPodMiniT = document.querySelector(".menuolPodMiniT");
    const menuolPodMiniF = document.querySelector(".menuolPodMiniF");
    const facaretdownO = document.querySelector(".fa-caret-downO");
    const facaretdownS = document.querySelector(".fa-caret-downS");
    const facaretdownT = document.querySelector(".fa-caret-downT");
    const facaretdownF = document.querySelector(".fa-caret-downF");
    menuolVMiniO.classList.toggle("activeOL");
    menuolUMiniO.classList.toggle("activeLi");
    facaretdownO.classList.toggle("activeFa");
    menuolVMiniS.classList.remove("activeOL");
    menuolVMiniT.classList.remove("activeOL");
    menuolVMiniD.classList.remove("activeOL");
    menuolPodMiniS.classList.remove("activeLi");
    menuolPodMiniT.classList.remove("activeLi");
    menuolPodMiniF.classList.remove("activeLi");
    facaretdownS.classList.remove("activeFa");
    facaretdownT.classList.remove("activeFa");
    facaretdownF.classList.remove("activeFa");
}
export function menuolMiniS() {
    const menuolVMiniS = document.querySelector(".menuolVMiniS");
    const menuolPodMiniS = document.querySelector(".menuolPodMiniS");
    const menuolVMiniO = document.querySelector(".menuolVMiniO");
    const menuolVMiniT = document.querySelector(".menuolVMiniT");
    const menuolVMiniD = document.querySelector(".menuolVMiniF");
    const menuolUMiniO = document.querySelector(".menuolUMiniO");
    const menuolPodMiniT = document.querySelector(".menuolPodMiniT");
    const menuolPodMiniF = document.querySelector(".menuolPodMiniF");
    const facaretdownO = document.querySelector(".fa-caret-downO");
    const facaretdownS = document.querySelector(".fa-caret-downS");
    const facaretdownT = document.querySelector(".fa-caret-downT");
    const facaretdownF = document.querySelector(".fa-caret-downF");
    menuolVMiniS.classList.toggle("activeOL");
    menuolPodMiniS.classList.toggle("activeLi");
    facaretdownS.classList.toggle("activeFa");
    menuolVMiniO.classList.remove("activeOL");
    menuolVMiniT.classList.remove("activeOL");
    menuolVMiniD.classList.remove("activeOL");
    menuolUMiniO.classList.remove("activeLi");
    menuolPodMiniT.classList.remove("activeLi");
    menuolPodMiniF.classList.remove("activeLi");
    facaretdownO.classList.remove("activeFa");
    facaretdownT.classList.remove("activeFa");
    facaretdownF.classList.remove("activeFa");
}
export function menuolMiniT() {
    const menuolVMiniT = document.querySelector(".menuolVMiniT");
    const menuolPodMiniT = document.querySelector(".menuolPodMiniT");
    const menuolVMiniO = document.querySelector(".menuolVMiniO");
    const menuolVMiniS = document.querySelector(".menuolVMiniS");
    const menuolVMiniD = document.querySelector(".menuolVMiniF");
    const menuolUMiniO = document.querySelector(".menuolUMiniO");
    const menuolPodMiniS = document.querySelector(".menuolPodMiniS");
    const menuolPodMiniF = document.querySelector(".menuolPodMiniF");
    const facaretdownO = document.querySelector(".fa-caret-downO");
    const facaretdownS = document.querySelector(".fa-caret-downS");
    const facaretdownT = document.querySelector(".fa-caret-downT");
    const facaretdownF = document.querySelector(".fa-caret-downF");
    menuolVMiniT.classList.toggle("activeOL");
    menuolPodMiniT.classList.toggle("activeLi");
    facaretdownT.classList.toggle("activeFa");
    menuolVMiniO.classList.remove("activeOL");
    menuolVMiniS.classList.remove("activeOL");
    menuolVMiniD.classList.remove("activeOL");
    menuolUMiniO.classList.remove("activeLi");
    menuolPodMiniS.classList.remove("activeLi");
    menuolPodMiniF.classList.remove("activeLi");
    facaretdownO.classList.remove("activeFa");
    facaretdownS.classList.remove("activeFa");
    facaretdownF.classList.remove("activeFa");
}
export function menuolMiniF() {
    const menuolVMiniF = document.querySelector(".menuolVMiniF");
    const menuolPodMiniF = document.querySelector(".menuolPodMiniF");
    const menuolVMiniO = document.querySelector(".menuolVMiniO");
    const menuolUMiniO = document.querySelector(".menuolUMiniO");
    const menuolPodMiniS = document.querySelector(".menuolPodMiniS");
    const menuolPodMiniT = document.querySelector(".menuolPodMiniT");
    const menuolVMiniS = document.querySelector(".menuolVMiniS");
    const menuolVMiniT = document.querySelector(".menuolVMiniT");
    const facaretdownO = document.querySelector(".fa-caret-downO");
    const facaretdownS = document.querySelector(".fa-caret-downS");
    const facaretdownT = document.querySelector(".fa-caret-downT");
    const facaretdownF = document.querySelector(".fa-caret-downF");
    menuolVMiniF.classList.toggle("activeOL");
    menuolPodMiniF.classList.toggle("activeLi");
    facaretdownF.classList.toggle("activeFa");
    menuolVMiniO.classList.remove("activeOL");
    menuolVMiniS.classList.remove("activeOL");
    menuolVMiniT.classList.remove("activeOL");
    menuolUMiniO.classList.remove("activeLi");
    menuolPodMiniS.classList.remove("activeLi");
    menuolPodMiniT.classList.remove("activeLi");
    facaretdownO.classList.remove("activeFa");
    facaretdownS.classList.remove("activeFa");
    facaretdownT.classList.remove("activeFa");
}
